name: Run unit test
inputs:
  package-name:
    description: 'Name of the package'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - uses: ./.github/actions/setup

    # Find current PR's number
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr

    - name: Run unit tests
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        working-directory: ./packages/${{ inputs.package-name }}
        test-script: yarn workspace @editorjs/${{ inputs.package-name }} test
        package-manager: yarn
        prnumber: ${{ steps.findPr.outputs.number }}