name: Unit tests
inputs:
  working-directory:
    description: 'Path to the ./packages/name_of_your_package_folder'
    required: true
  package-name:
    description: 'A full name of the package'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
    - uses: ./.github/actions/setup

    - uses: ./.github/actions/build
      with:
        package-name: ${{ inputs.package-name }}

    - name: Run unit tests with coverage
      shell: bash
      run: |
        yarn workspace ${{ inputs.package-name }} test:coverage

    - name: Upload coverage artifact (PRs only)
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/upload-artifact@v7
      with:
        name: test-report
        path: |
          ${{ inputs.working-directory }}/coverage
          ${{ inputs.working-directory }}/jest-report.json
        retention-days: 3

    - name: Run base coverage action
      if: ${{ github.event_name == 'pull_request' }}
      uses: ./.github/actions/base-coverage
      with:
        package-name: ${{ inputs.package-name }}
        working-directory: ${{ inputs.working-directory }}

