extends:
  - codex/ts

ignorePatterns:
  - node_modules
  - dist

# Eslint seems to not recognize WeakMap as a global
globals:
  WeakMap: readonly

overrides:
  - files:
      - '**/*.test.ts'
      - '**/*.spec.ts'
    env:
      jest: true
