extends:
  - codex/ts

ignorePatterns:
  - node_modules
  - dist

# Eslint seems to not recognize WeakMap as a global
globals:
  WeakMap: readonly

plugins:
  - import

rules:
  import/extensions:
    - error
    - always
  '@typescript-eslint/no-unsafe-declaration-merging':
    - 0
  # @todo: remove when we setup eslint to correctly handle the types
  '@typescript-eslint/no-unsafe-call':
    - 0
  '@typescript-eslint/no-unsafe-member-access':
    - 0
  '@typescript-eslint/no-unsafe-assignment':
    - 0
  '@typescript-eslint/no-unsafe-argument':
    - 0
  'jsdoc/require-returns-type':
    - 0
env:
  browser: true

overrides:
  - files:
      - '**/*.test.ts'
      - '**/*.spec.ts'
    env:
      jest: true
