name: Mutation tests for all files
description: Run mutation tests for all files of a given package

inputs:
  package-name:
    description: 'Name of the package'
    required: true
  stryker_dashboard_api_key:
    description: 'Stryker dashboard api key'
    required: true

runs:
  using: "composite"
  steps:
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run mutation tests
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ inputs.stryker_dashboard_api_key }}
        shell: bash
        id: run-mutation-tests
        run: yarn workspace ${{ inputs.package-name }} test:mutations --dashboard.version main --dashboard.module ${{ inputs.package-name }}
