name: Core check
on:
  pull_request:

jobs:
  package-check:
    uses: ./.github/workflows/package-check.yml
    with:
      package-name: '@editorjs/core'
      working-directory: './packages/core'
      include-mutations: true
    secrets:
      stryker_dashboard_api_key: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

