name: Dom-adapters check
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ESLint check
        uses: ./.github/actions/lint
        with:
          package-name: '@editorjs/dom-adapters'

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        uses: ./.github/actions/unit-tests
        with:
          working-directory: './packages/dom-adapters'
          package-name: '@editorjs/dom-adapters'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the package
        uses: ./.github/actions/build
        with:
          package-name: '@editorjs/dom-adapters'

  mutation-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run mutation tests for changed files
        if: ${{ github.event_name == 'push' }}
        uses: ./.github/actions/mutation-tests-changed-files
        with:
          package-name: '@editorjs/dom-adapters'
          working-directory: './packages/dom-adapters'
          stryker_dashboard_api_key: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

      - name: Run mutation tests for all files
        if: ${{ github.event_name == 'merge_group' }}
        uses: ./.github/actions/mutation-tests-all-files
        with:
          package-name: '@editorjs/dom-adapters'
          working-directory: './packages/dom-adapters'
          stryker_dashboard_api_key: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
