name: Merge queue workflow runner for model package
on:
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - uses: ./.github/actions/setup
      - name: Run ESLint check
        run: yarn workspace @editorjs/model lint:ci

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - uses: ./.github/actions/setup
      - name: Run unit tests
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ./packages/model
          test-script: yarn workspace @editorjs/model test
          package-manager: yarn

  mutation-tests:
    runs-on: ubuntu-latest
    env:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - uses: ./.github/actions/setup

      - name: Run mutation tests
        id: run-mutation-tests
        run: yarn workspace @editorjs/model test:mutations --dashboard.version main


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - uses: ./.github/actions/setup
      - name: Build the package
        run: yarn workspace @editorjs/model build
