name: Model check
on:
  pull_request:
  merge_group:

jobs:
  package-check:
    uses: ./.github/workflows/package-check.yml
    with:
      package-name: '@editorjs/model'
      working-directory: './packages/model'
      include-mutations: true
    secrets:
      stryker_dashboard_api_key: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

