name: Publish packages to NPM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/

      - run: corepack enable

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build all packages
        run: yarn workspaces foreach -Apt run build

      - name: Publish changed packages
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn workspaces foreach -At --no-private npm publish --access public --tolerate-republish
