name: OT server check
on:
  pull_request:
  merge_group:

jobs:
  package-check:
    uses: ./.github/workflows/package-check.yml
    with:
      package-name: '@editorjs/ot-server'
      working-directory: './packages/ot-server'
      include-mutations: false
    secrets:
      stryker_dashboard_api_key: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

