name: OT server check
on:
  pull_request:
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: yarn

      - name: Build the package
        uses: ./.github/actions/build
        with:
          package-name: '@editorjs/ot-server'

      - name: Run ESLint check
        uses: ./.github/actions/lint
        with:
          package-name: '@editorjs/ot-server'

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: yarn

      - name: Build the package
        uses: ./.github/actions/build
        with:
          package-name: '@editorjs/ot-server'

      - name: Run unit tests
        uses: ./.github/actions/unit-tests
        with:
          package-name: '@editorjs/ot-server'
          working-directory: './packages/ot-server'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build the package
        uses: ./.github/actions/build
        with:
          package-name: '@editorjs/ot-server'

  report:
    name: Aggregate and post report
    if: ${{ github.ref != 'refs/heads/main' && github.head_ref != 'main' }}
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate aggregated report and comment
        uses: ./.github/actions/aggregate-report
        with:
          package-name: '@editorjs/ot-server'

