name: Playground check
on:
  pull_request:
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ESLint check
        uses: ./.github/actions/lint
        with:
          package-name: '@editorjs/document-playground'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the package
        uses: ./.github/actions/build
        with:
          package-name: '@editorjs/document-playground'
