name: SDK check
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run ESLint check
        uses: ./.github/actions/lint
        with:
          package-name: '@editorjs/sdk'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build the package
        uses: ./.github/actions/build
        with:
          package-name: '@editorjs/sdk'

  report:
    name: Aggregate and post report
    if: ${{ github.ref != 'refs/heads/main' && github.head_ref != 'main' }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate aggregated report and comment
        uses: ./.github/actions/aggregate-report
        with:
          package-name: '@editorjs/sdk'

